FROM python:3.5.0

RUN mkdir /src/
WORKDIR /src/backend/

ADD requirements.txt /src/backend/

RUN pip install -r requirements.txt

RUN apt-get update && apt-get -y install cron
RUN touch /var/log/cron.log

ADD . /src/

EXPOSE 8000

ENTRYPOINT python manage.py runserver 0.0.0.0:8000