# Generated by Django 2.0.3 on 2018-03-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=63)),
                ('music', models.CharField(max_length=63)),
                ('description', models.TextField()),
            ],
        ),
    ]
