version: '3'

services:
  backend_ms:
    build: ./backend
    command: bash -c "python manage.py migrate
      && python manage.py retrieve_available_countries
      && service cron start
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/src/backend
    ports:
      - "8000:8000"
    depends_on: ["db"]
    restart: unless-stopped
  frontend_ms:
    build: ./frontend
    ports:
    - "3000:3000"
    links:
    - backend_ms
    volumes:
    - ./frontend/:/src/frontend
    depends_on: ["backend_ms"]
  db:
    build: ./backend/data/
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    restart: always
    ports:
    - "8010:5432"
    volumes:
    - ./backend/data/postgres-data:/var/lib/postgresql/data
