version: '3'

services:
  backend_ms:
    build: ./backend
    command: cron start
    volumes:
      - ./backend/:/src/backend
    ports:
      - "8000:8000"
  frontend_ms:
    build: ./frontend
    ports:
    - "3000:3000"
    links:
    - backend_ms
    volumes:
    - ./frontend/:/src/frontend
    depends_on: ["backend_ms"]
  db:
    build: ./backend/data/
    restart: always
    ports:
    - "8010:5432"
    volumes:
    - ./backend/data/postgres-data:/var/lib/postgresql/data
